### ISSUE TITLE
How to output the enter key

### ISSUE THREAD

**Issue by boesi** [donniebreve/touchcursor-linux#41]
Hi

Thanks for this great software. I have only one small problem: I can't output the enter key.

My key bindings:
KEY_H=KEY_LEFT
KEY_J=KEY_DOWN
KEY_K=KEY_UP
KEY_L=KEY_RIGHT
KEY_N=KEY_HOME
KEY_M=KEY_END
KEY_D=KEY_DELETE
KEY_E=KEY_ENTER
KEY_B=KEY_SPACE

All work except for the enter key.

**Comment by Adda0** [comment]
Hello, glad you find TouchCursor useful. I agree that this is a strange behaviour. I use `KEY_ENTER` all the time and never had the issue. Therefore, I presume the issue is on your end, as in makes itself evident on your system.

Just to be sure, you did restart the service with
```sh
systemctl --user restart touchcursor.service
```
after you added the `KEY_E=KEY_ENTER` line (and saved the file), right?

Could you try binding the enter key to other key that appears to be working (such as `KEY_B`, for example) and bind something else to `KEY_E` to make sure the issue is not linked to `KEY_E` specifically? Do not forget to restart the service again with the above command.

Which kernel version do you use? Run `uname -r` to find out.
Could you run the following command to ensure no errors are logged when restarting the service, too?
```sh
systemctl --user restart touchcursor.service; sleep 5; journalctl -e
```
Look for a line containing `Started Touch Cursor Service` and then see below this line for additional logs from touchcursor service. What do you get?

@donniebreve It occurs to me now that we do not have any verbose logging mode to output every operation TouchCursor does to a log file for debugging purposes such as this. Well, except for a few commented out debug prints such as [this](https://github.com/donniebreve/touchcursor-linux/blob/6e5b5d65e62dede0d71c72521559cf799efe1a92/src/touchcursor.c#L51) or [this one](https://github.com/donniebreve/touchcursor-linux/blob/6e5b5d65e62dede0d71c72521559cf799efe1a92/src/emit.c#L13). I will make an issue for that.

**Comment by boesi** [comment]
> Hello, glad you find TouchCursor useful. I agree that this is a strange behaviour. I use `KEY_ENTER` all the time and never had the issue. Therefore, I presume the issue is on your end, as in makes itself evident on your system.

Yes, you are right, and it was all my fault. First I had the binding `KEY_E=KEY_RETURN` which obviously wasn't working. After looking in [input-event-codes.h](https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h) (great that the link is in the config file), I changed the binding to `KEY_E=KEY_ENTER`. But instead of restarting the service, I just looked at its status.

So thanks for your nice hint, I missed an important step.
